apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: flux

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-2
  labels:
    app.kubernetes.io/name: flux
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-2
  labels:
    app.kubernetes.io/name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-2
subjects:
- kind: ServiceAccount
  name: flux
  namespace: ethereum-2
