apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: flux
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: flux
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flux
  updatePolicy:
    updateMode: Auto
