apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-to-sd
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: prometheus-to-sd
  annotations:
    iam.gke.io/gcp-service-account: prometheus-to-sd@allyoucanstake-dev.iam.gserviceaccount.com
automountServiceAccountToken: false
