apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-headless
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: jaeger
spec:
  clusterIP: None
  ports:
  - name: http-zipkin
    port: 9411
    targetPort: 0
  - name: http-grpc
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - name: http-c-binary-trft
    port: 14268
    targetPort: 0
  selector:
    app.kubernetes.io/name: jaeger

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: jaeger
spec:
  ports:
  - name: http-zipkin
    port: 9411
    targetPort: 0
  - name: http-grpc
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - name: http-c-binary-trft
    port: 14268
    targetPort: 0
  selector:
    app.kubernetes.io/name: jaeger

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: jaeger
spec:
  ports:
  - name: http-query
    port: 16686
    targetPort: 16686
  selector:
    app.kubernetes.io/name: jaeger

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: jaeger
spec:
  clusterIP: None
  ports:
  - name: zk-compact-trft
    port: 5775
    protocol: UDP
    targetPort: 0
  - name: config-rest
    port: 5778
    targetPort: 0
  - name: jg-compact-trft
    port: 6831
    protocol: UDP
    targetPort: 0
  - name: jg-binary-trft
    port: 6832
    protocol: UDP
    targetPort: 0
  selector:
    app.kubernetes.io/name: jaeger
