apiVersion: k8s.linki.space/v1alpha1
kind: EncryptedSecret
metadata:
  name: keystore
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: validator
spec:
  provider: GCP
  keyID: keyRings/ethereum-2/cryptoKeys/validator
  data:
    keymanageropts: CiQAAH9IkyePkuEnDf1/S2rqtyJC0PbawK3Q4xE7wrfAjjQ2plUSvQEqugEKFAoMv9yXclTeyvenKzypENLjjoQHEocBCn8HJMg4QKbyIwFQ+A0cWIrbwUXlA4y50uP3g9XTIwepYpVVQ+puXwkPTVvol+FWCkHEqaWULeJcaQJAp6XdV510iBRGVcQtGlKUjkJtjighuYelornlbRoteCb1LhZu9007gT0CbCxAenBtyZZAhe10wt00hFq+b1GD2trqzjorEOHW2+MBGhgKEIkJFjzi1eex+J+Kzr1njbsQ3rrwvwI=
    validatorprivatekey86833f841f39: CiQAAH9Ikx3YSW6AfdAG0/YzQ7fJwVo/LuqSUAe0vScGF3aMoqQS4QQq3gQKFAoMW7HHsoQL2P9qBGoZEOjyo+gPEqsECqIEKzGBbxojEvg30ghJJBqKeIPA8yruUbEVf2Gybpshg+p/yy0G3YQqP7y2H9CN3oMdcuGdt01vgGuyd/c37jc8Rnj9V8hfiBRry21zIHaMLeUiq+UZk4hF5T9lG7Bqnm4LlWZyMlqH6UyrvtOx+qRv06ifBO+95ECBB4sjvUiixUywq0Tyg8Wsb/kJzBJ5VV0RYslgkj2Tiqu1tc7jdtc0EdRUe/o+uSG4MtzfMuMWgtvF+rJHyc86n5XptD31ovJYo4YhWaENg0kB91C+OktT5x/1Qr5QEStS22/V8CfG2mMoCRTQg2dSvDPEpWxkOJs2ocdAwxpDacQ4xo/Vec481nnpgH7ZVSghMAtZhoGZG1Ltww+pbBzQ5d7+dw/Wd7jctLN8BYjVhas+I1lKn38e/U3n+/H4InwYCVQwer0eg1ERAqV/zSTrw5Hlk7eF+F0lSasetMZZhDFo413m4Gl3f0kqINfDYIvVjgCbLcCACFX36CvOY/LHAECu6+GJ/VeTi1gU/N2f8+iN5NBWEGrB8V4dkVDYwTcBGEmPHza+lCdvlyllcFDHicfPT1NJz/aeOxgty0rRINxQVVl7JLrgZzXzpXH3sWGh+FMJejnj4ztoDPG+9zpvinjjkD9SBBjvNwwEPjFfCSfnJRHTzZY9wN3WQTBgYmj+X53Rxb2kFNXm43DpxcV0FA2GtRzHnfseLf6AmVK6IXnHFWu3lL5BHPO2EMn8n8MOGhgKEDOnbikOJicd6vbWglvskusQyc7tqwk=
