apiVersion: v1
kind: ServiceAccount
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
  annotations:
    iam.gke.io/gcp-service-account: encrypted-secrets@allyoucanstake-dev.iam.gserviceaccount.com

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
rules:
# main functionality
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "list", "update", "watch"]
- apiGroups: ["k8s.linki.space"]
  resources: ["encryptedsecrets"]
  verbs: ["list", "watch"]
# sending events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# leader election
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
roleRef:
  kind: Role
  name: encrypted-secrets
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: encrypted-secrets

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
spec:
  displayName: Encrypted Secrets

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
spec:
  member: serviceAccount:encrypted-secrets@allyoucanstake-dev.iam.gserviceaccount.com
  role: roles/cloudkms.cryptoKeyDecrypter
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/allyoucanstake-dev

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: encrypted-secrets
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: encrypted-secrets
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: encrypted-secrets
  bindings:
  - role: roles/iam.workloadIdentityUser
    members:
    - serviceAccount:allyoucanstake-dev.svc.id.goog[ethereum-2/encrypted-secrets]
    - serviceAccount:allyoucanstake-dev.svc.id.goog[wanchain-2/encrypted-secrets]
