apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: "1.18.1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/version: "1.18.1"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
    spec:
      containers:
      - args:
        - --query.ui-config=/etc/config/ui.json
        - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: docker.io/jaegertracing/all-in-one:1.18.1
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 15
        name: jaeger
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
        - containerPort: 14267
          name: c-tchan-trft
        - containerPort: 14268
          name: c-binary-trft
        - containerPort: 16686
          name: query
        - containerPort: 14269
          name: admin-http
        - containerPort: 14250
          name: grpc
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/config
          name: jaeger-ui-configuration-volume
          readOnly: true
        - mountPath: /etc/jaeger/sampling
          name: jaeger-sampling-configuration-volume
          readOnly: true
      serviceAccountName: jaeger
      volumes:
      - configMap:
          items:
          - key: ui
            path: ui.json
          name: jaeger-ui-configuration
        name: jaeger-ui-configuration-volume
      - configMap:
          items:
          - key: sampling
            path: sampling.json
          name: jaeger-sampling-configuration
        name: jaeger-sampling-configuration-volume
