apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jaeger
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: jaeger
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jaeger
  updatePolicy:
    updateMode: Auto
