apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kube-state-metrics
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-state-metrics
  updatePolicy:
    updateMode: Auto
