apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@allyoucanstake-dev.iam.gserviceaccount.com

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-2
  labels:
    app.kubernetes.io/name: external-dns
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-2
  labels:
    app.kubernetes.io/name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-2
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: ethereum-2

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: external-dns
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: external-dns
spec:
  displayName: ExternalDNS

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: external-dns
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: external-dns
spec:
  member: serviceAccount:external-dns@allyoucanstake-dev.iam.gserviceaccount.com
  role: roles/dns.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/allyoucanstake-dev

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: external-dns
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: external-dns
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: external-dns
  bindings:
  - role: roles/iam.workloadIdentityUser
    members:
    - serviceAccount:allyoucanstake-dev.svc.id.goog[ethereum-2/external-dns]
