apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@allyoucanstake-dev.iam.gserviceaccount.com

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-2
  labels:
    app.kubernetes.io/name: external-dns
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-2
  labels:
    app.kubernetes.io/name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-2
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: ethereum-2
