apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: grafana
  annotations:
    iam.gke.io/gcp-service-account: grafana@allyoucanstake-dev.iam.gserviceaccount.com
automountServiceAccountToken: false

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: grafana
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: grafana
spec:
  displayName: Grafana

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: grafana
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: grafana
spec:
  member: serviceAccount:grafana@allyoucanstake-dev.iam.gserviceaccount.com
  role: roles/monitoring.viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/allyoucanstake-dev

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: grafana
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: grafana
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: grafana
  bindings:
  - role: roles/iam.workloadIdentityUser
    members:
    - serviceAccount:allyoucanstake-dev.svc.id.goog[ethereum-2/grafana]
