apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - name: http
    port: 3000
    nodePort: 30300
    targetPort: http
