apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: grafana
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: grafana
  updatePolicy:
    updateMode: Auto
