apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: elrond
  namespace: elrond
  labels:
    app.kubernetes.io/name: elrond
spec:
  allow:
  - protocol: tcp
    ports:
    - "31300"
  - protocol: udp
    ports:
    - "31200"
  networkRef:
    external: allyoucanstake-dev
  targetServiceAccounts:
  - external: allyoucanstake-dev@allyoucanstake-dev.iam.gserviceaccount.com
