apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: elrond
  namespace: elrond
  labels:
    app.kubernetes.io/name: elrond
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: elrond
  updatePolicy:
    updateMode: Auto
