apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: slasher
  namespace: ethereum-2
  labels:
    app.kubernetes.io/name: slasher
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: slasher
  policyTypes:
  - Ingress
  ingress:
  # allow the beacon chain to connect to the rpc endpoint
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: beacon-chain
    ports:
    - protocol: TCP
      port: 4002
  # allow the validator to connect to the rpc endpoint
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: validator
    ports:
    - protocol: TCP
      port: 4002
  # allow prometheus to scrape the metrics endpoint
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - protocol: TCP
      port: 8082
  # allow prometheus-to-sd to scrape the metrics endpoint
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus-to-sd
    ports:
    - protocol: TCP
      port: 8082
